"""User_Thread_Position

Revision ID: 5990f965d255
Revises: afb8709e5c78
Create Date: 2018-12-13 14:14:08.428299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5990f965d255'
down_revision = 'afb8709e5c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user__thread__position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('last_post_read', sa.Integer(), nullable=True),
    sa.Column('user_views', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('thread_position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_position',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('thread_id', sa.INTEGER(), nullable=True),
    sa.Column('last_post_read', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('user__thread__position')
    # ### end Alembic commands ###
