"""user thread combination unique in utp

Revision ID: 70b22989c294
Revises: 5990f965d255
Create Date: 2018-12-13 14:47:51.445964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b22989c294'
down_revision = '5990f965d255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_thread_position', 'user__thread__position', ['user_id', 'thread_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_thread_position', 'user__thread__position', type_='unique')
    # ### end Alembic commands ###
