version: '3.1'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: melly
      MYSQL_USER: melly
      MYSQL_PASSWORD: saskatchewan
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - my-network

  web:
    image: melonfacedoom/melly:latest
    restart: always
    depends_on:
      - db
    links:
      - db
    environment:
      SECRET_KEY: "wiejfoipwaehgoubwguajbfaj"
      DATABASE_URL: mysql+pymysql://melly:saskatchewan@db/melly
    networks:
      my-network:
        aliases:
          - melly

  nginx:
    image: nginx:1.17.4
    container_name: nginx
    depends_on:
      - web
    networks:
      - my-network
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  db_data: {}
networks:
  my-network:
