version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: melly
      MYSQL_USER: melly
      MYSQL_PASSWORD: saskatchewan
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  web:
    image: melonfacedoom/melly:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8000:5000
    links:
      - db
    environment:
      SECRET_KEY: "wiejfoipwaehgoubwguajbfaj"
      DATABASE_URL: mysql+pymysql://melly:saskatchewan@db/melly

volumes:
  db_data: {}