"""post edit history

Revision ID: 3182c778044f
Revises: 4a9fdb74b21f
Create Date: 2019-09-14 22:52:30.566639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3182c778044f'
down_revision = '4a9fdb74b21f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('body_formatted', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('original_post_id', sa.Integer(), nullable=True),
    sa.Column('edited_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edited_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['original_post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edit_history_timestamp'), 'edit_history', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edit_history_timestamp'), table_name='edit_history')
    op.drop_table('edit_history')
    # ### end Alembic commands ###
