"""emoji name unqiue

Revision ID: 3f8713e704ce
Revises: 2f9bd8d94356
Create Date: 2019-09-11 14:30:55.470477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8713e704ce'
down_revision = '2f9bd8d94356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("emoji") as batch_op:
        batch_op.create_unique_constraint('unique_name', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("emoji") as batch_op:
        batch_op.drop_constraint('unique_name', ['name'])
    # ### end Alembic commands ###
