"""added user join timestamp

Revision ID: 4a9fdb74b21f
Revises: 3f8713e704ce
Create Date: 2019-09-13 17:58:42.645633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9fdb74b21f'
down_revision = '3f8713e704ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('join_timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_join_timestamp'), 'user', ['join_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_join_timestamp'), table_name='user')
    op.drop_column('user', 'join_timestamp')
    # ### end Alembic commands ###
