"""renamed one emoji column

Revision ID: 966b101db7ff
Revises: fb0c797288fd
Create Date: 2019-04-08 16:00:12.256112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966b101db7ff'
down_revision = 'fb0c797288fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("emoji") as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=140), nullable=True))
        batch_op.drop_column('emoji_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("emoji") as batch_op:
        batch_op.add_column(sa.Column('emoji_name', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_column('name')
    # ### end Alembic commands ###
