"""change how user thread position is stored

Revision ID: d9ca4d211b85
Revises: 4f83556eb160
Create Date: 2019-01-08 16:36:45.874145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ca4d211b85'
down_revision = '4f83556eb160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__thread__position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_post_viewed_id', sa.Integer(), nullable=True))
        #batch_op.create_foreign_key(None, 'post', ['last_post_viewed_id'], ['id'])
        batch_op.create_foreign_key('last_post_viewed_id', 'post', ['last_post_viewed_id'], ['id'])
        batch_op.drop_column('last_post_viewed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__thread__position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_post_viewed', sa.INTEGER(), nullable=True))
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('last_post_viewed_id', type_='foreignkey')
        batch_op.drop_column('last_post_viewed_id')

    # ### end Alembic commands ###
