"""formatted post body column

Revision ID: f1cead6a0581
Revises: 966b101db7ff
Create Date: 2019-07-24 21:14:29.296043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1cead6a0581'
down_revision = '966b101db7ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mod_level', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_mod_level'), 'user', ['mod_level'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mod_level'), table_name='user')
    op.drop_column('user', 'mod_level')
    # ### end Alembic commands ###
